--- 
rackup: config/config.ru
pid: tmp/pids/thin.pid
address: 0.0.0.0
port: 3000
timeout: 30
log: log/thin.log
max_conns: 1024
require: []

environment: production
max_persistent_conns: 512
servers: 8
daemonize: true
chdir: /opt/SinMagick

